<?php

namespace Database\Seeders;

use App\Models\Listing;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ListingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $listings = [
            [
                'job_title' => 'Senior Software Engineer',
                'job_category' => 'Information Technology',
                'job_nature' => 'Full-time',
                'vacancy' => 3,
                'salary' => 80000,
                'location' => 'New York, NY',
                'description' => 'Seeking an experienced software engineer to join our dynamic team. Responsibilities include designing, coding, testing, and deploying software solutions.',
                'benefits' => 'Health insurance, retirement plan, flexible working hours',
                'responsibility' => 'Develop high-quality software solutions, participate in code reviews, troubleshoot and debug applications',
                'qualification' => 'Bachelor\'s degree in Computer Science or related field, 5+ years of experience in software development, proficiency in Java, Python, or similar languages',
                'keywords' => 'Software Engineer, Java, Full-stack, New York, IT',
                'company_name' => 'Tech Solutions Inc.',
                'company_location' => 'San Francisco, CA',
                'company_website' => 'www.techsolutions.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'job_title' => 'Marketing Manager',
                'job_category' => 'Marketing',
                'job_nature' => 'Contract',
                'vacancy' => 2,
                'salary' => 60000,
                'location' => 'Los Angeles, CA',
                'description' => 'We are looking for a skilled Marketing Manager to join our team. Responsibilities include developing marketing strategies, managing campaigns, and analyzing marketing data.',
                'benefits' => 'Bonus opportunities, remote work options',
                'responsibility' => 'Develop and implement marketing plans, oversee social media strategies, analyze campaign performance',
                'qualification' => 'Bachelor\'s degree in Marketing or related field, 3+ years of experience in marketing management, strong analytical skills',
                'keywords' => 'Marketing Manager, Campaigns, Social Media, Los Angeles',
                'company_name' => 'Global Marketing Solutions',
                'company_location' => 'New York, NY',
                'company_website' => 'www.globalmarketing.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'job_title' => 'Data Scientist',
                'job_category' => 'Data Science',
                'job_nature' => 'Full-time',
                'vacancy' => 1,
                'salary' => 90000,
                'location' => 'Chicago, IL',
                'description' => 'Join our data science team to analyze large datasets, build predictive models, and derive insights to drive business decisions.',
                'benefits' => 'Comprehensive benefits package, flexible working hours',
                'responsibility' => 'Analyze complex data sets, build machine learning models, communicate findings to stakeholders',
                'qualification' => 'Master\'s degree in Data Science, Statistics, or related field, experience with Python, R, SQL, and machine learning frameworks',
                'keywords' => 'Data Scientist, Machine Learning, Python, Chicago, Data Analysis',
                'company_name' => 'Data Insights Corp.',
                'company_location' => 'Chicago, IL',
                'company_website' => 'www.datainsights.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'job_title' => 'UX/UI Designer',
                'job_category' => 'Design',
                'job_nature' => 'Full-time',
                'vacancy' => 2,
                'salary' => 75000,
                'location' => 'San Francisco, CA',
                'description' => 'Seeking a creative UX/UI Designer to design intuitive and user-friendly interfaces for our web and mobile applications.',
                'benefits' => 'Health and wellness programs, company stock options',
                'responsibility' => 'Create wireframes, prototypes, and user flows, collaborate with product managers and developers, conduct usability testing',
                'qualification' => 'Bachelor\'s degree in Design, Human-Computer Interaction, or related field, proficiency in design tools such as Sketch, Adobe XD, or Figma',
                'keywords' => 'UX Designer, UI Designer, Design, San Francisco, Web Design',
                'company_name' => 'Creative Designs Ltd.',
                'company_location' => 'San Francisco, CA',
                'company_website' => 'www.creativedesigns.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'job_title' => 'Financial Analyst',
                'job_category' => 'Finance',
                'job_nature' => 'Full-time',
                'vacancy' => 1,
                'salary' => 85000,
                'location' => 'Boston, MA',
                'description' => 'We are hiring a Financial Analyst to provide financial planning and analysis support. Responsibilities include financial modeling, budgeting, and forecasting.',
                'benefits' => '401(k) matching, health insurance, professional development opportunities',
                'responsibility' => 'Prepare financial reports, analyze financial data, assist in budget preparation, monitor financial performance',
                'qualification' => 'Bachelor\'s degree in Finance, Economics, or related field, CPA or CFA certification preferred, proficiency in financial modeling and analysis tools',
                'keywords' => 'Financial Analyst, Finance, Boston, Budgeting',
                'company_name' => 'Financial Solutions Inc.',
                'company_location' => 'Boston, MA',
                'company_website' => 'www.financialsolutions.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'job_title' => 'HR Manager',
                'job_category' => 'Human Resources',
                'job_nature' => 'Full-time',
                'vacancy' => 1,
                'salary' => 70000,
                'location' => 'Seattle, WA',
                'description' => 'Seeking an experienced HR Manager to oversee all aspects of human resources management. Responsibilities include recruitment, employee relations, and HR policy development.',
                'benefits' => 'Generous vacation policy, remote work options',
                'responsibility' => 'Develop and implement HR strategies, manage recruitment and hiring processes, ensure compliance with labor regulations',
                'qualification' => 'Bachelor\'s degree in Human Resources, Business Administration, or related field, 5+ years of HR management experience, strong knowledge of labor laws',
                'keywords' => 'HR Manager, Human Resources, Recruitment, Seattle',
                'company_name' => 'HR Solutions Ltd.',
                'company_location' => 'Seattle, WA',
                'company_website' => 'www.hrsolutions.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'job_title' => 'Customer Support Specialist',
                'job_category' => 'Customer Service',
                'job_nature' => 'Full-time',
                'vacancy' => 3,
                'salary' => 55000,
                'location' => 'Dallas, TX',
                'description' => 'We are hiring Customer Support Specialists to provide exceptional customer service and resolve customer issues via phone, email, and chat.',
                'benefits' => 'Paid training, career growth opportunities',
                'responsibility' => 'Respond to customer inquiries, troubleshoot issues, escalate complex cases to appropriate teams, maintain customer records',
                'qualification' => 'High school diploma or equivalent, previous customer service experience, excellent communication skills',
                'keywords' => 'Customer Support Specialist, Customer Service, Dallas, Communication Skills',
                'company_name' => 'Support Solutions Inc.',
                'company_location' => 'Dallas, TX',
                'company_website' => 'www.supportsolutions.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'job_title' => 'Operations Manager',
                'job_category' => 'Operations',
                'job_nature' => 'Full-time',
                'vacancy' => 1,
                'salary' => 90000,
                'location' => 'Houston, TX',
                'description' => 'Join our team as an Operations Manager to oversee daily operations, manage staff, and ensure efficient business processes.',
                'benefits' => 'Competitive salary, performance bonuses, comprehensive benefits package',
                'responsibility' => 'Develop operational strategies, monitor performance metrics, optimize processes, ensure compliance with safety and quality standards',
                'qualification' => 'Bachelor\'s degree in Business Administration or related field, 5+ years of experience in operations management, strong leadership skills',
                'keywords' => 'Operations Manager, Operations, Houston, Leadership',
                'company_name' => 'Operations Excellence Ltd.',
                'company_location' => 'Houston, TX',
                'company_website' => 'www.operations-excellence.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'job_title' => 'Legal Counsel',
                'job_category' => 'Legal',
                'job_nature' => 'Full-time',
                'vacancy' => 1,
                'salary' => 95000,
                'location' => 'Washington, D.C.',
                'description' => 'We are seeking a Legal Counsel to provide legal advice and support. Responsibilities include drafting contracts, advising on legal matters, and representing the company in legal proceedings.',
                'benefits' => 'Health insurance, retirement plan, professional development opportunities',
                'responsibility' => 'Draft and review legal documents, provide legal advice to management, ensure compliance with legal regulations',
                'qualification' => 'Law degree from an accredited law school, admission to the bar, 3+ years of experience in corporate law or related field',
                'keywords' => 'Legal Counsel, Legal, Washington DC, Corporate Law',
                'company_name' => 'Legal Solutions LLC',
                'company_location' => 'Washington, D.C.',
                'company_website' => 'www.legalsolutions.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'job_title' => 'Sales Manager',
                'job_category' => 'Sales',
                'job_nature' => 'Full-time',
                'vacancy' => 2,
                'salary' => 85000,
                'location' => 'Atlanta, GA',
                'description' => 'Join our sales team as a Sales Manager to lead sales initiatives, develop strategies, and drive revenue growth.',
                'benefits' => 'Uncapped commission structure, company car allowance, international travel opportunities',
                'responsibility' => 'Manage sales team, develop sales strategies, analyze market trends, build and maintain customer relationships',
                'qualification' => 'Bachelor\'s degree in Business Administration or related field, 5+ years of experience in sales management, proven track record of achieving sales targets',
                'keywords' => 'Sales Manager, Sales, Atlanta, Revenue Growth',
                'company_name' => 'Sales Solutions Ltd.',
                'company_location' => 'Atlanta, GA',
                'company_website' => 'www.salessolutions.com',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Insert data into database using Eloquent
        Listing::insert($listings);
    }
}
